version: '3.7'

services:

  ezserver:
    container_name: ezserver_api
    image: ezserver_api
    environment:
      CACHER: redis://ezserver_redis:6379
      PULSER: 5
      DATABASE: mongodb://ezserver_mongo:27017/ezwow
    depends_on:
      - ezserver_redis
      - ezserver_mongo
    restart: always
    volumes:
      -  ./public:./public
    ports: 
      - 3000:3000

  ezserver_redis:
    image: redis:alpine
    container_name: ezserver_redis
    restart: always

  ezserver_mongo:
    image : mongo
    container_name: chatops_mongo
    restart: always
    volumes:
      - database:/data/db

volumes:
  database:
