version: "2"

services:

  ezserver:
    container_name: ezserver_api
    image: docker.rassvet-nf.ru/ezserver
    environment:
      CACHER: redis://ezserver_redis:6379
      PULSER: 60
    depends_on:
      - ezserver_redis
    networks:
      - internal
      - default
    ports:
      - 44235:3000
    restart: always
    volumes:
      - database: /usr/app/database

  ezserver_redis:
    image: redis:alpine
    container_name: ezserver_redis
    networks:
      - internal
    restart: always

networks:
  internal:

volumes:
  database: