version: "2"

services:

  ezserver:
    container_name: ezserver_api
    image: docker.rassvet-nf.ru/ezserver
    environment:
      SERVICEDIR: src/services
      CACHER: redis://ezserver_redis
      LOGGER: "true"
      LOGLEVEL: info
      TRANSPORTER: nats://ezserver_nats:4222
      DB_CONNECTION: mariadb://ezserver:SDjjasdU*&Sdhbkasd@ezserver_db:3306/ezserver
    depends_on:
      - ezserver_nats
      - ezserver_redis
      - ezserver_db
    networks:
      - internal
      - default
    ports:
      - 127.0.0.1:44235:44235
    restart: always
    links:
      - ezserver_db

  ezserver_nats:
    image: nats
    container_name: ezserver_nats
    networks:
      - internal
    restart: always

  ezserver_redis:
    image: redis:alpine
    container_name: ezserver_redis
    networks:
      - internal
    restart: always
  
  ezserver_db:
    image: mariadb
    container_name: ezserver_db
    volumes:
      - dbdata2:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=SDjjasdU*&Sdhbkasd
      - MYSQL_DATABASE=ezserver
      - MYSQL_USER=ezserver
      - MYSQL_PASSWORD=SDjjasdU*&Sdhbkasd
    restart: always
    networks:
      - internal

networks:
  internal:

volumes:
  dbdata2: