version: "2"

services:

  ezserver:
    container_name: ezserver_api
    image: docker.rassvet-nf.ru/ezserver
    environment:
      CACHER: redis://ezserver_redis:6379
      PULSER: 5
      DATABASE: mongodb://ezserver_mongo:27017/ezwow
    depends_on:
      - ezserver_redis
      - ezserver_mongo
    networks:
      - internal
      - default
    ports:
      - 44235:3000
    restart: always

  ezserver_redis:
    image: redis:alpine
    container_name: ezserver_redis
    networks:
      - internal
    restart: always

  ezserver_mongo:
    image : mongo
    container_name: chatops_mongo
    restart: always
    volumes:
      - database:/data/db
    networks:
      - internal

networks:
  internal:

volumes:
  database: